from __future__ import annotations
ROWS = [
    ('host_header_injection', 'Host Header Injection', 82, 'http_protocol', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-17', '', '', 'host_derived_security_surface', 'untrusted_host_used_in_security_sensitive_output_observed', 'controlled_host_influence_observed', 'host_allowlist_enforced;canonical_origin_configured', 'host;x-forwarded-host;reset;absolute url;origin'),
    ('csv_injection', 'CSV / Formula Injection', 68, 'data_export', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-21', 'CWE-1236', '', 'spreadsheet_export_surface', 'untrusted_cell_formula_prefix_preserved', 'controlled_formula_interpretation_observed', 'spreadsheet_formula_neutralization_observed;export_as_plain_text_observed', 'csv;excel;spreadsheet;export;report'),
    ('prototype_pollution', 'Prototype Pollution', 88, 'object_integrity', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-22', 'CWE-1321', '', 'object_merge_surface', 'unsafe_recursive_merge_observed', 'controlled_prototype_property_pollution_observed', 'prototype_keys_rejected;safe_object_merge_observed;null_prototype_objects_used', 'merge;assign;object;json;config;settings'),
    ('unsafe_deserialization', 'Unsafe Deserialization', 95, 'object_integrity', 'manual_only', 'A08:2021 Software and Data Integrity Failures', '', 'CWE-502', 'CAPEC-586', 'serialized_object_input_surface', 'untrusted_deserialization_observed', 'controlled_unexpected_type_instantiation_observed', 'safe_data_only_deserializer_observed;type_allowlist_enforced;signed_serialized_data_verified', 'serialize;deserialize;pickle;object stream;binary formatter'),
    ('csrf', 'Cross-Site Request Forgery', 82, 'session_security', 'manual_only', 'A01:2021 Broken Access Control', 'WSTG-SESS-05', 'CWE-352', 'CAPEC-62', 'cookie_authenticated_state_change_surface', 'csrf_protection_missing_observed;origin_validation_missing_observed', 'controlled_cross_site_state_change_accepted', 'csrf_token_enforced;same_site_cookie_enforced;origin_or_referer_validation_enforced', 'update;delete;change;transfer;email;password;settings'),
    ('clickjacking', 'Clickjacking', 64, 'client_security', 'passive_live', 'A05:2021 Security Misconfiguration', 'WSTG-CLNT-09', 'CWE-1021', 'CAPEC-103', 'sensitive_ui_frame_surface', 'frame_ancestors_protection_missing_observed', 'sensitive_page_frameable_observed', 'x_frame_options_enforced;csp_frame_ancestors_enforced', 'account;settings;admin;payment;confirm'),
    ('html_injection', 'HTML Injection', 72, 'client_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-CLNT-03', 'CWE-79', '', 'html_rendering_surface', 'untrusted_html_markup_rendered_observed', 'controlled_html_structure_injection_observed', 'html_output_encoding_observed;html_sanitizer_enforced', 'preview;content;description;message;html'),
    ('css_injection', 'CSS Injection', 66, 'client_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-CLNT-05', 'CWE-79', '', 'style_injection_surface', 'untrusted_css_rendered_observed', 'controlled_css_rule_applied_observed', 'css_value_allowlist_enforced;style_context_encoding_observed', 'style;theme;css;color;font'),
    ('client_side_resource_manipulation', 'Client-Side Resource Manipulation', 78, 'client_security', 'manual_only', 'A03:2021 Injection', 'WSTG-CLNT-06', '', '', 'client_resource_url_surface', 'untrusted_resource_url_assignment_observed', 'controlled_external_resource_selection_observed', 'resource_origin_allowlist_enforced;trusted_static_resource_map_observed', 'src;href;resource;asset;image;script;stylesheet'),
    ('xssi', 'Cross-Site Script Inclusion', 74, 'data_exposure', 'manual_only', 'A01:2021 Broken Access Control', 'WSTG-CLNT-13', '', '', 'script_readable_sensitive_response_surface', 'cross_origin_script_readable_sensitive_data_observed', 'controlled_cross_origin_sensitive_data_exposure_observed', 'non_executable_json_response_observed;anti_xssi_prefix_observed;cross_origin_access_blocked', 'json;callback;script;profile;account;data'),
    ('reverse_tabnabbing', 'Reverse Tabnabbing', 58, 'client_security', 'passive_live', 'A05:2021 Security Misconfiguration', 'WSTG-CLNT-14', 'CWE-1022', '', 'new_tab_external_link_surface', 'opener_reference_exposed_observed', 'external_tab_can_control_opener_observed', 'noopener_enforced;noreferrer_enforced;coop_isolation_enforced', 'target=_blank;external link;new tab'),
    ('client_side_template_injection', 'Client-Side Template Injection', 80, 'client_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-CLNT-15', 'CWE-1336', '', 'client_template_expression_surface', 'untrusted_client_template_expression_observed', 'controlled_client_template_expression_evaluated', 'client_template_literal_encoding_observed;expression_syntax_disabled', 'template;angular;vue;mustache;handlebars;expression'),
    ('browser_storage_exposure', 'Browser Storage Exposure', 72, 'data_exposure', 'passive_live', 'A02:2021 Cryptographic Failures', 'WSTG-CLNT-12', 'CWE-922', '', 'browser_storage_surface', 'sensitive_data_in_browser_storage_observed', 'sensitive_token_persisted_in_web_storage_observed', 'no_sensitive_browser_storage_observed;http_only_cookie_storage_observed', 'localstorage;sessionstorage;indexeddb;token;storage'),
    ('security_headers', 'HTTP Security Header Weakness', 60, 'configuration', 'passive_live', 'A05:2021 Security Misconfiguration', 'WSTG-CONF-12;WSTG-CONF-14', 'CWE-693', '', 'browser_security_header_surface', 'required_security_header_missing_or_invalid_observed', 'security_header_policy_ineffective_observed', 'required_security_headers_valid_observed', 'content-security-policy;x-content-type-options;referrer-policy;permissions-policy'),
    ('tls_hsts_weakness', 'TLS / HSTS Weakness', 78, 'transport_security', 'passive_live', 'A02:2021 Cryptographic Failures', 'WSTG-CONF-07;WSTG-CRYP-01', 'CWE-319;CWE-326;CWE-295', '', 'transport_security_surface', 'weak_tls_configuration_observed;hsts_policy_weak_or_missing_observed', 'plaintext_sensitive_transport_observed;invalid_certificate_trust_observed', 'modern_tls_enforced;hsts_policy_valid_observed;certificate_validation_valid', 'https;tls;hsts;certificate;strict-transport-security'),
]
