from __future__ import annotations
ROWS = [
    ('subdomain_takeover', 'Subdomain Takeover', 88, 'dns_cloud', 'manual_only', 'A05:2021 Security Misconfiguration', 'WSTG-CONF-10', '', '', 'dangling_dns_dependency_surface', 'dns_points_to_unclaimed_service_observed', 'provider_resource_claimability_confirmed_authorized', 'provider_resource_owned;dns_target_active;provider_claim_prevented', 'cname;dns;github pages;s3;azure;heroku;cloudfront'),
    ('cloud_storage_exposure', 'Cloud Storage Exposure', 86, 'cloud_security', 'passive_live', 'A05:2021 Security Misconfiguration', 'WSTG-CONF-11', 'CWE-732', '', 'cloud_storage_surface', 'cloud_object_listing_public_observed;cloud_object_write_public_observed', 'sensitive_cloud_object_publicly_readable_observed', 'cloud_storage_private_policy_observed;signed_access_required', 'bucket;blob;storage;s3;gcs;azure'),
    ('backup_unreferenced_file_exposure', 'Backup / Unreferenced File Exposure', 78, 'data_exposure', 'passive_live', 'A05:2021 Security Misconfiguration', 'WSTG-CONF-04', 'CWE-530', '', 'backup_or_unreferenced_file_surface', 'backup_file_publicly_reachable_observed;unreferenced_sensitive_file_publicly_reachable_observed', 'sensitive_backup_content_exposed_observed', 'backup_files_not_publicly_reachable;sensitive_content_absent', 'backup;bak;old;copy;zip;tar;sql;~'),
    ('admin_interface_exposure', 'Admin Interface Exposure', 80, 'configuration', 'passive_live', 'A05:2021 Security Misconfiguration', 'WSTG-CONF-05', 'CWE-749', '', 'administrative_interface_surface', 'admin_interface_publicly_reachable_observed', 'unauthenticated_admin_function_exposed_observed', 'admin_interface_network_restricted;admin_authentication_enforced', 'admin;manage;management;console;dashboard;internal'),
    ('path_confusion', 'Path Confusion', 70, 'routing_security', 'manual_only', 'A05:2021 Security Misconfiguration', 'WSTG-CONF-13', '', '', 'path_normalization_boundary_surface', 'frontend_backend_path_normalization_disagreement_observed', 'controlled_path_policy_bypass_observed', 'canonical_path_normalization_consistent;ambiguous_paths_rejected', 'path;proxy;rewrite;normalize;semicolon;suffix'),
    ('jwt_weakness', 'JWT Weakness', 92, 'token_security', 'manual_only', 'A07:2021 Identification and Authentication Failures', 'WSTG-SESS-10', 'CWE-347;CWE-345', '', 'jwt_authentication_surface', 'jwt_verification_weakness_observed;jwt_claim_validation_missing_observed', 'controlled_invalid_jwt_accepted_observed', 'jwt_signature_verification_enforced;jwt_issuer_audience_time_claims_enforced;jwt_algorithm_allowlist_enforced', 'jwt;bearer;authorization;token;jws'),
    ('oauth_oidc_weakness', 'OAuth / OIDC Weakness', 92, 'identity_protocol', 'manual_only', 'A07:2021 Identification and Authentication Failures', 'WSTG-ATHZ-05', '', '', 'oauth_oidc_flow_surface', 'oauth_redirect_validation_weak_observed;oauth_state_nonce_pkce_weak_observed;oauth_token_binding_weak_observed', 'controlled_oauth_flow_security_bypass_observed', 'oauth_redirect_uri_exact_match_enforced;oauth_state_nonce_enforced;pkce_enforced;oauth_token_lifetime_and_replay_controls_enforced', 'oauth;openid;oidc;authorize;callback;redirect_uri;pkce;code_challenge'),
    ('logging_monitoring_weakness', 'Security Logging / Monitoring Weakness', 58, 'observability', 'manual_only', 'A09:2021 Security Logging and Monitoring Failures', '', 'CWE-778;CWE-223', '', 'security_relevant_event_surface', 'security_event_not_logged_observed;security_log_lacks_required_context_observed', 'controlled_security_event_missing_from_audit_log_observed', 'security_event_logging_verified;audit_log_integrity_and_context_verified', 'audit;log;security event;monitor;alert'),
    ('exceptional_condition_fail_open', 'Fail-Open / Exceptional Condition Weakness', 84, 'error_handling', 'manual_only', 'A05:2021 Security Misconfiguration', 'WSTG-ERRH-01', 'CWE-636', '', 'security_control_error_path_surface', 'security_control_error_path_observed', 'controlled_fail_open_behavior_observed', 'fail_closed_behavior_verified;error_path_preserves_authorization', 'error;exception;timeout;fallback;unavailable'),
    ('weak_cryptography', 'Weak Cryptographic Primitive / Usage', 80, 'cryptography', 'passive_live', 'A02:2021 Cryptographic Failures', 'WSTG-CRYP-04', 'CWE-327;CWE-328', '', 'cryptographic_operation_surface', 'deprecated_cryptographic_primitive_observed;weak_key_or_mode_configuration_observed', 'security_relevant_weak_crypto_use_confirmed', 'approved_cryptographic_primitive_observed;strong_key_and_mode_configuration_observed', 'md5;sha1;des;rc4;ecb;crypto;cipher;hash'),
    ('software_data_integrity', 'Software / Data Integrity Failure', 88, 'supply_chain', 'manual_only', 'A08:2021 Software and Data Integrity Failures', '', 'CWE-494;CWE-353', '', 'trusted_update_or_data_pipeline_surface', 'integrity_verification_missing_observed;unsigned_update_or_artifact_trusted_observed', 'controlled_tampered_artifact_accepted_observed', 'artifact_signature_verification_enforced;integrity_hash_verification_enforced;trusted_update_channel_enforced', 'update;artifact;package;plugin;firmware;manifest;signature'),
    ('dependency_supply_chain', 'Dependency / Supply-Chain Risk', 82, 'supply_chain', 'passive_live', 'A06:2021 Vulnerable and Outdated Components', '', 'CWE-1104;CWE-829', '', 'third_party_component_surface', 'known_vulnerable_component_match_observed;unmaintained_security_critical_component_observed;untrusted_dependency_source_observed', 'reachable_vulnerable_component_path_confirmed', 'component_version_not_affected;vulnerable_feature_not_reachable;dependency_source_pinned_and_verified', 'package;dependency;library;component;version;vendor'),
    ('web_cache_poisoning', 'Web Cache Poisoning', 84, 'http_cache', 'manual_only', 'A05:2021 Security Misconfiguration', '', '', '', 'shared_cache_key_surface', 'unkeyed_input_affects_cacheable_response_observed;cache_key_normalization_mismatch_observed', 'controlled_cache_variant_persisted_observed', 'cache_key_includes_security_relevant_input;response_not_shared_cacheable;cache_bypass_for_dynamic_content', 'cache;vary;x-forwarded-host;x-original-url;cdn'),
]
