from __future__ import annotations
ROWS = [
    ('reflected_xss', 'Reflected XSS', 84, 'client_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-01', 'CWE-79', 'CAPEC-63', 'reflected_input_surface', 'unescaped_reflection_observed;unsafe_html_context_observed', 'reflected_script_execution_observed', 'contextual_output_encoding_observed;csp_blocks_inline_execution;input_not_reflected', 'search;query;message;error;return;callback'),
    ('stored_xss', 'Stored XSS', 88, 'client_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-02', 'CWE-79', 'CAPEC-63', 'persistent_user_content_surface', 'stored_content_rendered_unescaped;unsafe_persistent_html_context_observed', 'stored_script_execution_observed', 'stored_output_encoding_observed;stored_sanitization_observed;csp_blocks_inline_execution', 'comment;profile;bio;description;message;review;post;name'),
    ('http_verb_tampering', 'HTTP Verb Tampering', 74, 'access_control', 'passive_live', 'A01:2021 Broken Access Control', 'WSTG-INPV-03;WSTG-CONF-06', 'CWE-650', '', 'method_authorization_surface', 'method_policy_inconsistency_observed', 'unauthorized_method_access_observed', 'method_authorization_consistent;unsupported_methods_rejected', 'method;put;patch;delete;options;head'),
    ('http_parameter_pollution', 'HTTP Parameter Pollution', 72, 'input_parsing', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-04', 'CWE-235', '', 'duplicate_parameter_surface', 'ambiguous_parameter_parsing_observed', 'duplicate_parameter_security_bypass_observed', 'duplicate_parameters_rejected;canonical_parameter_parsing_observed', 'query;filter;redirect;role;id;next'),
    ('orm_injection', 'ORM Injection', 86, 'server_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-05', 'CWE-564', 'CAPEC-109', 'orm_query_surface', 'unsafe_orm_query_construction_observed', 'orm_query_semantics_influenced_observed', 'orm_parameter_binding_observed;typed_orm_filter_enforced', 'filter;where;order;sort;query;find;search'),
    ('xml_injection', 'XML Injection', 82, 'server_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-07', 'CWE-91', '', 'xml_parser_surface', 'unsafe_xml_construction_observed', 'xml_structure_influence_observed', 'xml_schema_validation_enforced;xml_special_characters_escaped', 'xml;soap;saml;feed;document'),
    ('xml_external_entity', 'XML External Entity', 92, 'server_injection', 'manual_only', 'A05:2021 Security Misconfiguration', 'WSTG-INPV-07', 'CWE-611', 'CAPEC-221', 'xml_external_entity_surface', 'external_entity_resolution_enabled_observed', 'controlled_external_entity_resolution_observed', 'external_entities_disabled;dtd_processing_disabled;secure_xml_parser_observed', 'xml;doctype;dtd;soap;saml'),
    ('ssi_injection', 'SSI Injection', 88, 'server_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-08', 'CWE-97', '', 'ssi_processing_surface', 'unsafe_ssi_interpolation_observed', 'ssi_directive_evaluation_observed', 'ssi_disabled;ssi_input_encoded', 'shtml;ssi;include;echo;exec'),
    ('xpath_injection', 'XPath Injection', 84, 'server_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-09', 'CWE-643', 'CAPEC-83', 'xpath_query_surface', 'unsafe_xpath_construction_observed', 'xpath_query_semantics_influenced_observed', 'xpath_parameterization_observed;xpath_input_escaping_observed', 'xpath;xml;search;filter;node'),
    ('imap_smtp_injection', 'IMAP/SMTP Injection', 82, 'server_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-10', 'CWE-93', '', 'mail_protocol_command_surface', 'unsafe_mail_command_construction_observed', 'mail_command_boundary_influenced_observed', 'mail_command_parameterization_observed;mail_input_strictly_validated', 'imap;smtp;mail;recipient;subject;folder'),
    ('code_injection', 'Code Injection', 97, 'server_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-11', 'CWE-94', 'CAPEC-242', 'dynamic_code_execution_surface', 'unsafe_dynamic_code_construction_observed', 'benign_code_evaluation_observed', 'dynamic_code_execution_disabled;code_input_allowlist_enforced', 'eval;expression;script;code;execute'),
    ('file_inclusion', 'File Inclusion', 92, 'server_injection', 'manual_only', 'A01:2021 Broken Access Control;A03:2021 Injection', 'WSTG-INPV-11', 'CWE-98', 'CAPEC-252', 'dynamic_file_include_surface', 'unsafe_file_include_path_observed', 'controlled_unintended_file_include_observed', 'include_path_allowlist_enforced;remote_include_disabled;include_root_constrained', 'include;template;view;page;file;module'),
    ('format_string_injection', 'Format String Injection', 90, 'server_injection', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-13', 'CWE-134', 'CAPEC-67', 'format_string_surface', 'user_controlled_format_string_observed', 'controlled_format_interpretation_observed', 'constant_format_string_observed;safe_format_api_observed', 'printf;format;sprintf;logger;message'),
    ('http_response_splitting', 'HTTP Response Splitting / CRLF', 84, 'http_protocol', 'manual_only', 'A03:2021 Injection', 'WSTG-INPV-15', 'CWE-113', '', 'response_header_input_surface', 'unsanitized_response_header_input_observed', 'controlled_crlf_header_boundary_observed', 'response_header_crlf_rejected;header_value_encoding_observed', 'redirect;location;filename;download;header;cookie'),
    ('http_request_smuggling', 'HTTP Request Smuggling', 94, 'http_protocol', 'manual_only', 'A05:2021 Security Misconfiguration', 'WSTG-INPV-16', 'CWE-444', '', 'multi_hop_http_parser_surface', 'http_parser_framing_disagreement_observed', 'controlled_request_desynchronization_observed', 'consistent_message_framing_observed;ambiguous_framing_rejected', 'proxy;gateway;load balancer;content-length;transfer-encoding'),
]
